"""add google calendar columns to users

Revision ID: 8344beea275c
Revises: 32900de7fd86
Create Date: 2026-06-04 21:09:10.869845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8344beea275c'
down_revision: Union[str, Sequence[str], None] = '32900de7fd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('calendar_connected', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calendar_connected')
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###
