"""add start and end datetime to tasks

Revision ID: eccfe0a7501f
Revises: 8344beea275c
Create Date: 2026-06-04 22:28:41.201561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccfe0a7501f'
down_revision: Union[str, Sequence[str], None] = '8344beea275c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_date_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('end_date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'end_date_time')
    op.drop_column('tasks', 'start_date_time')
    # ### end Alembic commands ###
