"""rename type to category in tasks

Revision ID: 32900de7fd86
Revises: 68a12f18a280
Create Date: 2026-05-29 22:20:40.829968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32900de7fd86'
down_revision: Union[str, Sequence[str], None] = '68a12f18a280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('tasks', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
